augment_input_features: true
augment_output_features: true
batch_size: 2
commitment_cost: 0.25
data_root: ./
decay: 0.0
decoder_type: deconvolutional
embedding_dim: 64
export_one_hot_features: false
features_path: features
input_dim: 256
input_features_dim: 47
input_features_filters: 13
input_features_type: mfcc
jitter_probability: 0.12
learning_rate: 0.0002
length: 7680
normalize: true
normalizer_path: ../data/vctk/vctk-mfcc-stats.pickle
num_embeddings: 44
num_epochs: 15
num_hiddens: 768
num_residual_layers: 2
num_workers: 16
output_features_dim: 47
output_features_filters: 13
output_features_type: mfcc
quantize: 256
record_codebook_stats: false
record_gradient_stats: false
res_type: kaiser_fast
residual_channels: 768
sampling_rate: 16000
start_epoch: 0
top_db: 20
train_val_split: 0.8
trainer_type: convolutional
use_cuda: true
use_data_parallel: false
use_device: cuda:0
use_jitter: false
use_kaiming_normal: false
use_speaker_conditioning: false
verbose: false
